engines:
  duplication:
    enabled: false
    config:
      languages:
        javascript:
          mass_threshold: 20
ratings:
  paths:
  - "**.js"
exclude_paths:
- "**.spec.js"
- "node_modules/**/*"
- "server/templates"
