language: node_js
node_js:
  - "8"
env:
  global:
    - export NODE_ENV=test
    - DATABASE_URL_TEST=postgres://jmjbrcfp:FvHq4yiSgqDPdzPa0v1NzLITLEgee5NI@pellefant.db.elephantsql.com:5432/jmjbrcfp
script:
  - npm test
