language: node_js
node_js:
  - "8"
env:
  global:
    - export NODE_ENV=test
before_script:
  - npm install -g codeclimate-test-reporter
script:
  - npm test
after_success:
  - codeclimate-test-reporter < coverage/lcov.info
  - npm run coverage
